# Generated by Django 2.2 on 2019-04-22 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='NewPerson',
        ),
    ]
