# Generated by Django 2.2 on 2019-04-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0004_userprofileinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewPerson',
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
