# Generated by Django 2.2 on 2019-04-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0005_auto_20190425_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.CharField(default='default description', max_length=264),
        ),
    ]
